//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO_124_16_ADO.NET_IvanovVA_MyDBApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\ITMO_124-16_A" +
            "DO.NET_IvanovVA_MyDBApp.mdf;Integrated Security=True")]
        public string ITMO_124_16_ADO_NET_IvanovVA_MyDBAppConnectionString {
            get {
                return ((string)(this["ITMO_124_16_ADO_NET_IvanovVA_MyDBAppConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLNCLIRDA11;Data Source=(LocalDB)\\MSSQLLocalDB;Password=1111;User ID=Ad" +
            "min;Initial Catalog=\"C:\\USERS\\VLADI\\ONEDRIVE\\РАБОЧИЙ СТОЛ\\ADO.NET\\ITMO_124-16_AD" +
            "O.NET_IVANOVVA_MYDBAPP\\ITMO_124-16_ADO.NET_IVANOVVA_MYDBAPP.MDF\"")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
    }
}
